training:
  n_iter: 10000
  n_iter_inner: 10
  log_freq: 100
  adapt_batch_size: False

model:
  name: cellot
  kernel_init_fxn:
    b: 0.1
    name: uniform
  softplus_W_kernels: false
  g:
    fnorm_penalty: 1
  hidden_units: [64, 64, 64, 64]
  init: identity

optim:
  beta1: 0.5
  beta2: 0.9
  lr: 0.0001
  optimizer: Adam
  weight_decay: 0